# .github/workflows/release.yml
name: Release

# Trigger this workflow when a tag matching v*.*.* (e.g., v1.0.0) is pushed
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_TERM_COLOR: always # Force color output in cargo logs
  APP_NAME: rename-episodes # Define the application name here

jobs:
  # Job 1: Create a draft release placeholder on GitHub
  create_release:
    name: Create Release Draft
    runs-on: ubuntu-latest
    outputs:
      # Pass the upload URL to subsequent jobs
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release Draft
        id: create_release
        uses: actions/create-release@v1
        env:
          # This token is provided by Actions, needs write permissions to repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }} # Use the tag that triggered the workflow
          release_name: Release ${{ github.ref_name }} # Release title (e.g., "Release v1.0.0")
          draft: true # Create as a draft first
          prerelease: false # Mark as a full release, not pre-release

  # Job 2: Build binaries for different platforms and upload them
  build_release:
    name: Build Release Assets
    needs: create_release # Run only after the draft release is created
    strategy:
      matrix:
        # Define only the parts that fundamentally change the build process
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            asset_suffix: linux-x64.tar.gz
          - target: x86_64-pc-windows-gnu
            os: ubuntu-latest
            asset_suffix: windows-x64.zip
          - target: x86_64-apple-darwin
            os: macos-latest
            asset_suffix: macos-x64.tar.gz
          - target: aarch64-apple-darwin
            os: macos-latest
            asset_suffix: macos-arm64.tar.gz

    runs-on: ${{ matrix.os }} # Run on the OS specified in the matrix configuration
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checks out your repository under $GITHUB_WORKSPACE

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable # Installs Rust
        with:
          targets: ${{ matrix.target }} # Installs support for the specific target platform

      # Add linker dependencies if needed for cross-compiling (e.g., Windows from Linux)
      - name: Install linker for Windows cross-compilation (if needed)
        if: matrix.os == 'ubuntu-latest' && contains(matrix.target, 'windows')
        run: |
          sudo apt-get update && sudo apt-get install -y gcc-mingw-w64-x86-64

      - name: Build binary
        # Run cargo build for the specified target in release mode
        run: cargo build --release --target ${{ matrix.target }}

      # Determine executable path and final asset name based on OS within steps
      - name: Set executable name and path
        id: paths
        shell: bash
        run: |
          if [[ "${{ matrix.target }}" == *windows* ]]; then
            echo "exe_name=${{ env.APP_NAME }}.exe" >> $GITHUB_OUTPUT
            echo "exe_path=target/${{ matrix.target }}/release/${{ env.APP_NAME }}.exe" >> $GITHUB_OUTPUT
          else
            echo "exe_name=${{ env.APP_NAME }}" >> $GITHUB_OUTPUT
            echo "exe_path=target/${{ matrix.target }}/release/${{ env.APP_NAME }}" >> $GITHUB_OUTPUT
          fi
          echo "asset_filename=${{ env.APP_NAME }}-${{ github.ref_name }}-${{ matrix.asset_suffix }}" >> $GITHUB_OUTPUT

      # --- Packaging Steps ---
      - name: Package artifact (Linux/macOS)
        shell: bash
        # Run if the target is Linux or macOS
        if: contains(matrix.target, 'linux') || contains(matrix.target, 'darwin')
        run: |
          # Ensure LICENSE exists before packaging
          if [ ! -f LICENSE ]; then echo "LICENSE file not found!" >&2; exit 1; fi
          tar czvf "${{ steps.paths.outputs.asset_filename }}" -C target/${{ matrix.target }}/release "${{ steps.paths.outputs.exe_name }}" -C . README.md LICENSE

      - name: Package artifact (Windows)
        shell: bash
        # Run if the target is Windows
        if: contains(matrix.target, 'windows')
        run: |
          # Ensure LICENSE exists before packaging
          if [ ! -f LICENSE ]; then echo "LICENSE file not found!" >&2; exit 1; fi
          zip -j "${{ steps.paths.outputs.asset_filename }}" "${{ steps.paths.outputs.exe_path }}" README.md LICENSE
      # --- End Packaging Steps ---
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }} # URL from the first job
          # Use the asset filename determined in the 'paths' step
          asset_path: ./${{ steps.paths.outputs.asset_filename }}
          asset_name: ${{ steps.paths.outputs.asset_filename }}
          asset_content_type: application/octet-stream
